"""Country data for global OSINT search template generation.

Each entry maps a country name to its capital and region, used to auto-generate
search templates for countries not already covered by hand-curated templates.
"""

COUNTRIES = [
    {"name": "Afghanistan", "capital": "Kabul", "region": "South Asia"},
    {"name": "Albania", "capital": "Tirana", "region": "Europe"},
    {"name": "Algeria", "capital": "Algiers", "region": "North Africa"},
    {"name": "Angola", "capital": "Luanda", "region": "Sub-Saharan Africa"},
    {"name": "Argentina", "capital": "Buenos Aires", "region": "South America"},
    {"name": "Armenia", "capital": "Yerevan", "region": "Caucasus"},
    {"name": "Australia", "capital": "Canberra", "region": "Oceania"},
    {"name": "Austria", "capital": "Vienna", "region": "Europe"},
    {"name": "Azerbaijan", "capital": "Baku", "region": "Caucasus"},
    {"name": "Bangladesh", "capital": "Dhaka", "region": "South Asia"},
    {"name": "Belarus", "capital": "Minsk", "region": "Europe"},
    {"name": "Belgium", "capital": "Brussels", "region": "Europe"},
    {"name": "Belize", "capital": "Belmopan", "region": "Central America"},
    {"name": "Benin", "capital": "Porto-Novo", "region": "West Africa"},
    {"name": "Bhutan", "capital": "Thimphu", "region": "South Asia"},
    {"name": "Bolivia", "capital": "La Paz", "region": "South America"},
    {"name": "Bosnia and Herzegovina", "capital": "Sarajevo", "region": "Europe"},
    {"name": "Botswana", "capital": "Gaborone", "region": "Sub-Saharan Africa"},
    {"name": "Brazil", "capital": "Brasilia", "region": "South America"},
    {"name": "Brunei", "capital": "Bandar Seri Begawan", "region": "Southeast Asia"},
    {"name": "Bulgaria", "capital": "Sofia", "region": "Europe"},
    {"name": "Burkina Faso", "capital": "Ouagadougou", "region": "West Africa"},
    {"name": "Burundi", "capital": "Gitega", "region": "East Africa"},
    {"name": "Cambodia", "capital": "Phnom Penh", "region": "Southeast Asia"},
    {"name": "Cameroon", "capital": "Yaounde", "region": "Central Africa"},
    {"name": "Canada", "capital": "Ottawa", "region": "North America"},
    {"name": "Central African Republic", "capital": "Bangui", "region": "Central Africa"},
    {"name": "Chad", "capital": "N'Djamena", "region": "Central Africa"},
    {"name": "Chile", "capital": "Santiago", "region": "South America"},
    {"name": "Colombia", "capital": "Bogota", "region": "South America"},
    {"name": "Costa Rica", "capital": "San Jose", "region": "Central America"},
    {"name": "Croatia", "capital": "Zagreb", "region": "Europe"},
    {"name": "Cuba", "capital": "Havana", "region": "Caribbean"},
    {"name": "Cyprus", "capital": "Nicosia", "region": "Europe"},
    {"name": "Czech Republic", "capital": "Prague", "region": "Europe"},
    {"name": "Democratic Republic of the Congo", "capital": "Kinshasa", "region": "Central Africa"},
    {"name": "Denmark", "capital": "Copenhagen", "region": "Europe"},
    {"name": "Djibouti", "capital": "Djibouti", "region": "East Africa"},
    {"name": "Dominican Republic", "capital": "Santo Domingo", "region": "Caribbean"},
    {"name": "East Timor", "capital": "Dili", "region": "Southeast Asia"},
    {"name": "Ecuador", "capital": "Quito", "region": "South America"},
    {"name": "Egypt", "capital": "Cairo", "region": "North Africa"},
    {"name": "El Salvador", "capital": "San Salvador", "region": "Central America"},
    {"name": "Equatorial Guinea", "capital": "Malabo", "region": "Central Africa"},
    {"name": "Eritrea", "capital": "Asmara", "region": "East Africa"},
    {"name": "Estonia", "capital": "Tallinn", "region": "Europe"},
    {"name": "Ethiopia", "capital": "Addis Ababa", "region": "East Africa"},
    {"name": "Fiji", "capital": "Suva", "region": "Oceania"},
    {"name": "Finland", "capital": "Helsinki", "region": "Europe"},
    {"name": "France", "capital": "Paris", "region": "Europe"},
    {"name": "Gabon", "capital": "Libreville", "region": "Central Africa"},
    {"name": "Gambia", "capital": "Banjul", "region": "West Africa"},
    {"name": "Georgia", "capital": "Tbilisi", "region": "Caucasus"},
    {"name": "Germany", "capital": "Berlin", "region": "Europe"},
    {"name": "Ghana", "capital": "Accra", "region": "West Africa"},
    {"name": "Greece", "capital": "Athens", "region": "Europe"},
    {"name": "Guatemala", "capital": "Guatemala City", "region": "Central America"},
    {"name": "Guinea", "capital": "Conakry", "region": "West Africa"},
    {"name": "Guinea Bissau", "capital": "Bissau", "region": "West Africa"},
    {"name": "Guyana", "capital": "Georgetown", "region": "South America"},
    {"name": "Honduras", "capital": "Tegucigalpa", "region": "Central America"},
    {"name": "Hungary", "capital": "Budapest", "region": "Europe"},
    {"name": "Iceland", "capital": "Reykjavik", "region": "Europe"},
    {"name": "India", "capital": "New Delhi", "region": "South Asia"},
    {"name": "Indonesia", "capital": "Jakarta", "region": "Southeast Asia"},
    {"name": "Iraq", "capital": "Baghdad", "region": "Middle East"},
    {"name": "Ireland", "capital": "Dublin", "region": "Europe"},
    {"name": "Italy", "capital": "Rome", "region": "Europe"},
    {"name": "Ivory Coast", "capital": "Yamoussoukro", "region": "West Africa"},
    {"name": "Jamaica", "capital": "Kingston", "region": "Caribbean"},
    {"name": "Japan", "capital": "Tokyo", "region": "East Asia"},
    {"name": "Jordan", "capital": "Amman", "region": "Middle East"},
    {"name": "Kazakhstan", "capital": "Astana", "region": "Central Asia"},
    {"name": "Kenya", "capital": "Nairobi", "region": "East Africa"},
    {"name": "Kosovo", "capital": "Pristina", "region": "Europe"},
    {"name": "Kuwait", "capital": "Kuwait City", "region": "Middle East"},
    {"name": "Kyrgyzstan", "capital": "Bishkek", "region": "Central Asia"},
    {"name": "Laos", "capital": "Vientiane", "region": "Southeast Asia"},
    {"name": "Latvia", "capital": "Riga", "region": "Europe"},
    {"name": "Lebanon", "capital": "Beirut", "region": "Middle East"},
    {"name": "Lesotho", "capital": "Maseru", "region": "Sub-Saharan Africa"},
    {"name": "Liberia", "capital": "Monrovia", "region": "West Africa"},
    {"name": "Libya", "capital": "Tripoli", "region": "North Africa"},
    {"name": "Lithuania", "capital": "Vilnius", "region": "Europe"},
    {"name": "Luxembourg", "capital": "Luxembourg City", "region": "Europe"},
    {"name": "Macedonia", "capital": "Skopje", "region": "Europe"},
    {"name": "Madagascar", "capital": "Antananarivo", "region": "Sub-Saharan Africa"},
    {"name": "Malawi", "capital": "Lilongwe", "region": "Sub-Saharan Africa"},
    {"name": "Malaysia", "capital": "Kuala Lumpur", "region": "Southeast Asia"},
    {"name": "Mali", "capital": "Bamako", "region": "West Africa"},
    {"name": "Malta", "capital": "Valletta", "region": "Europe"},
    {"name": "Mauritania", "capital": "Nouakchott", "region": "West Africa"},
    {"name": "Mexico", "capital": "Mexico City", "region": "North America"},
    {"name": "Moldova", "capital": "Chisinau", "region": "Europe"},
    {"name": "Mongolia", "capital": "Ulaanbaatar", "region": "East Asia"},
    {"name": "Montenegro", "capital": "Podgorica", "region": "Europe"},
    {"name": "Morocco", "capital": "Rabat", "region": "North Africa"},
    {"name": "Mozambique", "capital": "Maputo", "region": "Sub-Saharan Africa"},
    {"name": "Namibia", "capital": "Windhoek", "region": "Sub-Saharan Africa"},
    {"name": "Nepal", "capital": "Kathmandu", "region": "South Asia"},
    {"name": "Netherlands", "capital": "Amsterdam", "region": "Europe"},
    {"name": "New Zealand", "capital": "Wellington", "region": "Oceania"},
    {"name": "Nicaragua", "capital": "Managua", "region": "Central America"},
    {"name": "Niger", "capital": "Niamey", "region": "West Africa"},
    {"name": "Nigeria", "capital": "Abuja", "region": "West Africa"},
    {"name": "North Korea", "capital": "Pyongyang", "region": "East Asia"},
    {"name": "Norway", "capital": "Oslo", "region": "Europe"},
    {"name": "Oman", "capital": "Muscat", "region": "Middle East"},
    {"name": "Pakistan", "capital": "Islamabad", "region": "South Asia"},
    {"name": "Panama", "capital": "Panama City", "region": "Central America"},
    {"name": "Papua New Guinea", "capital": "Port Moresby", "region": "Oceania"},
    {"name": "Paraguay", "capital": "Asuncion", "region": "South America"},
    {"name": "Peru", "capital": "Lima", "region": "South America"},
    {"name": "Philippines", "capital": "Manila", "region": "Southeast Asia"},
    {"name": "Poland", "capital": "Warsaw", "region": "Europe"},
    {"name": "Portugal", "capital": "Lisbon", "region": "Europe"},
    {"name": "Qatar", "capital": "Doha", "region": "Middle East"},
    {"name": "Republic of Serbia", "capital": "Belgrade", "region": "Europe"},
    {"name": "Republic of the Congo", "capital": "Brazzaville", "region": "Central Africa"},
    {"name": "Romania", "capital": "Bucharest", "region": "Europe"},
    {"name": "Rwanda", "capital": "Kigali", "region": "East Africa"},
    {"name": "Saudi Arabia", "capital": "Riyadh", "region": "Middle East"},
    {"name": "Senegal", "capital": "Dakar", "region": "West Africa"},
    {"name": "Sierra Leone", "capital": "Freetown", "region": "West Africa"},
    {"name": "Slovakia", "capital": "Bratislava", "region": "Europe"},
    {"name": "Slovenia", "capital": "Ljubljana", "region": "Europe"},
    {"name": "Solomon Islands", "capital": "Honiara", "region": "Oceania"},
    {"name": "Somalia", "capital": "Mogadishu", "region": "East Africa"},
    {"name": "South Africa", "capital": "Pretoria", "region": "Sub-Saharan Africa"},
    {"name": "South Korea", "capital": "Seoul", "region": "East Asia"},
    {"name": "South Sudan", "capital": "Juba", "region": "East Africa"},
    {"name": "Spain", "capital": "Madrid", "region": "Europe"},
    {"name": "Sri Lanka", "capital": "Colombo", "region": "South Asia"},
    {"name": "Sudan", "capital": "Khartoum", "region": "East Africa"},
    {"name": "Suriname", "capital": "Paramaribo", "region": "South America"},
    {"name": "Sweden", "capital": "Stockholm", "region": "Europe"},
    {"name": "Switzerland", "capital": "Bern", "region": "Europe"},
    {"name": "Syria", "capital": "Damascus", "region": "Middle East"},
    {"name": "Taiwan", "capital": "Taipei", "region": "East Asia"},
    {"name": "Tajikistan", "capital": "Dushanbe", "region": "Central Asia"},
    {"name": "Thailand", "capital": "Bangkok", "region": "Southeast Asia"},
    {"name": "The Bahamas", "capital": "Nassau", "region": "Caribbean"},
    {"name": "Togo", "capital": "Lome", "region": "West Africa"},
    {"name": "Trinidad and Tobago", "capital": "Port of Spain", "region": "Caribbean"},
    {"name": "Tunisia", "capital": "Tunis", "region": "North Africa"},
    {"name": "Turkey", "capital": "Ankara", "region": "Middle East"},
    {"name": "Turkmenistan", "capital": "Ashgabat", "region": "Central Asia"},
    {"name": "Uganda", "capital": "Kampala", "region": "East Africa"},
    {"name": "Ukraine", "capital": "Kyiv", "region": "Europe"},
    {"name": "United Arab Emirates", "capital": "Abu Dhabi", "region": "Middle East"},
    {"name": "United Kingdom", "capital": "London", "region": "Europe"},
    {"name": "United Republic of Tanzania", "capital": "Dodoma", "region": "East Africa"},
    {"name": "United States of America", "capital": "Washington", "region": "North America"},
    {"name": "Uruguay", "capital": "Montevideo", "region": "South America"},
    {"name": "Uzbekistan", "capital": "Tashkent", "region": "Central Asia"},
    {"name": "Vanuatu", "capital": "Port Vila", "region": "Oceania"},
    {"name": "Venezuela", "capital": "Caracas", "region": "South America"},
    {"name": "Vietnam", "capital": "Hanoi", "region": "Southeast Asia"},
    {"name": "Yemen", "capital": "Sanaa", "region": "Middle East"},
    {"name": "Zambia", "capital": "Lusaka", "region": "Sub-Saharan Africa"},
    {"name": "Zimbabwe", "capital": "Harare", "region": "Sub-Saharan Africa"},
]


def generate_country_template(country: dict) -> dict:
    """Generate a generic OSINT search template for a country."""
    name = country["name"]
    capital = country["capital"]
    return {
        "label": name,
        "topics": [
            f"{name} security",
            f"{name} military",
            f"{name} conflict",
            f"{name} political crisis",
        ],
        "location": name,
        "place_hints": [name, capital],
        "max_articles": 50,
    }
